### ISSUE TITLE
Trying to install SysID from github, not working in SDL

### ISSUE THREAD

**Issue by KjellRSeeq** [BYU-PRISM/Seeq#2]
A user at one of our customers would like to explore the SysID package shown in our Seeq gallery launched this week. I am trying to follow the install steps, screenshot below, and I am running into an issue at Step 3.
![image-2021-10-15-15-59-59-529](https://user-images.githubusercontent.com/92815457/137958807-9f51ae5c-be57-47bb-8b65-2c59b05c89d8.png)

 
I am able to create a new SDL project, run the terminal, run step 2 command. Then I shutdown that terminal and open a new one, per the video, and enter the command on step 3 - however, I get the following error when running that command (I also note that in my new terminal, I do not have the (base) prepending the command line. I am an Admin on the server.

![image-2021-10-15-16-01-36-938](https://user-images.githubusercontent.com/92815457/137958817-bb79fe8b-e367-4d7b-921c-40b171eec04c.png)

Is there something else I need to do in the project? My colleagues at Seeq tell me that we cannot use conda installs in Seeq Data Lab projects, therefore the Add On will not run for all users. Is there another way to install this package??

I'm following the steps from here: https://github.com/BYU-PRISM/Seeq/blob/main/README.md

**Comment by imanbabaei** [comment]
We tried to use a pre-built slycot package to avoid that error. Building slycot from the source code requires a compiler.
However, We simplified the installation procedure, and there is no need to install some packages based on slycot.

You can install the Seeq-SysID package by running `pip install seeq-sysid` in a new terminal.
[Installation Guide](https://github.com/BYU-PRISM/Seeq#user-installation-seeq-data-lab)

**Comment by KjellRSeeq** [comment]
Hey guys, this is working! App runs as expected in App Mode as well. Thanks for your help!
