### ISSUE TITLE
Application hanging after clicking identify

### ISSUE THREAD

**Issue by Selmane-Seeq** [BYU-PRISM/Seeq#38]
Unable to use System Identification Add-on.  After specifying the MV and CV as well as the training/validation time periods, click on identify results in the system hanging (the system id window).

This ticket is submitted on behalf of rohit.patwardhan@aramco.com from Saudi Aramco. Please contact him directly for a remote session or to share more information.

**Comment by Selmane-Seeq** [comment]
![image](https://user-images.githubusercontent.com/124570890/216949631-38db5c23-e177-46a1-8044-1e21418895b3.png)

This screenshot was sent by customer in Seeq Support Portal

**Comment by anvenkat18** [comment]
It looks like a training condition was used but there were no capsules for that training condition in the display range. This is currently causing the add-on to hang. @imanbabaei will be addressing this  in the next version. @Selmane-Seeq can the user try with capsules in the display range or skip using a condition for training (in which case the entire display range will be used to build the dynamic model)

**Comment by Selmane-Seeq** [comment]
Thank you @anvenkat18 for your swift reply. There's a SUP on this matter and I replied there. Let's see if the fix you propose will solve the problem.

**Comment by Selmane-Seeq** [comment]
Hello @anvenkat18, the issue remains even after having capsules in display pane or just using a training time window. this is customer replay:

"I do have capsules in my data range – see below from the Seeq workbench side. 
 
![image](https://user-images.githubusercontent.com/124570890/217385311-a87c9800-3a81-411c-bb05-34f374bdb307.png)

However, I do not see any data from the add-on side  

![image](https://user-images.githubusercontent.com/124570890/217385418-f4139394-a645-4e28-aefa-f4f0399f8b74.png)

 I have tried running it without any conditions, still don’t see any data."

**Comment by imanbabaei** [comment]
Hello @Selmane-Seeq,
Thank you very much!
We made some changes in our latest release, which improves the performance of the training and validation steps.
Please try `pip install seeq-sysid -U` and let us know if this solves the problem.
I highly recommend cleaning your data before using System Identification add-on.
