### ISSUE TITLE
Add-on Returns No Results When used on worksheets without conditions

### ISSUE THREAD

**Issue by KrisspyKreme** [BYU-PRISM/Seeq#4]
The SysId Add-on does not return any info when used on worksheets without conditions. Adding a condition to the worksheet causes the tool to work as expected. If this is expected, maybe include more info in the user guide
![SysID Blank Without Condition](https://user-images.githubusercontent.com/93542015/139711703-f6eeebdf-a6c4-45df-a4d6-df01f8d5856f.gif)

**Comment by imanbabaei** [comment]
Thank you for your feedback!
Issue fixed in the latest release (v0.0.6).
Please use `pip install seeq-sysid --upgrade` to update your package.
