### ISSUE TITLE
Nb extensions requirement updates 

### ISSUE THREAD

**Issue by jameshiggie** [BYU-PRISM/Seeq#46]
Suggestion to remove  'plotlywidget' from this list on line 13 in main.py. 

Upcoming updates to SDL lead to an error in sysID install on https://github.com/BYU-PRISM/Seeq/blob/d54a5c61225db02d2118f15a2cd6e385084721a9/SysID%20Addon/seeq_sysid/__main__.py#L13 for 'plotlywidget' after plotly>5.5.  Initial testing show this and other add-ons are not needed. Removing 'plotlywidget' from this list on line 13 in main.py works with plotly>5.10 and doesn't impact the functionally for sysID visualisations in initial testing.

**Comment by imanbabaei** [comment]
Thanks for the issue @jameshiggie!

**Comment by imanbabaei** [comment]
Suggestion applied in SysID v1.0.1.
